version: '3.3'

services:
  php:
    build:
      context: ./docker
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./:/var/www/phpstan
    depends_on:
      - mysql
      - mongo
    ports:
      - 127.0.0.1:8000:8000

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'

  mongo:
    image: mongo:3.4
    command: "--smallfiles --logpath=/dev/null"
