version: '3.3'

services:
  php:
    build:
      context: ./docker
    environment:
      COMPOSER_MEMORY_LIMIT: -1
    volumes:
      - ./:/var/www/phpstan
    links:
      - mysql
      - mongo

  mysql:
    image: mysql:5.7

  mongo:
    image: mongo:3.4
    command: "--smallfiles --logpath=/dev/null"
